server:
  port: 8030
spring:
  application:
    name: EurekaServerService
eureka:
  client:
    #表示是否将自己注册到Eureka-Server中，默认true
    register-with-eureka: false
    #false表示自己端就是注册中心，职责就是维护服务实例，并不需要去检索服务
    #Eureka启动时，默认拉取其它服务的信息，设置关闭即可正常运行
    fetch-registry: true
    #设置注册中心的地址，注意加空格，访问地址localhost:7001
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/

